import { useEffect, useState } from 'react'
import { IconArrowRight, IconDownload } from '../../components/Icons.jsx'
import { useReveal } from '../../lib/useReveal.js'
import logo from '../../assets/mediadores/IMAGENES/MEDIADORES DE CONVIVENCIA LOGO_Horizontal.png'
import heroImage from '../../assets/mediadores/IMAGENES/CARTILLA_MEDIADORES_PARTE1-03 (1).png'
import teamImage from '../../assets/mediadores/IMAGENES/CARTILLA_MEDIADORES_PARTE3_Mesa de trabajo 1.png'
import './mediadores.css'

const STATS = [
  ['5.203.118', 'personas impactadas', 'Acumulado 2024–2026'],
  ['295.278', 'actividades realizadas', 'Acumulado 2024–2026'],
  ['422', 'mediadores en Colombia', 'Promedio anual'],
  ['42', 'municipios con presencia', 'Cobertura territorial'],
]
const ZONES = ['Zona 1', 'Zona 2', 'Zona 3', 'Zona 4', 'Zona 5', 'Zona 6', 'Zona 7', 'Zona 8']

export default function MediadoresPage() {
  const [zone, setZone] = useState('Zona 1')
  useReveal()
  useEffect(() => { const h = window.location.hash.replace(/^#/, ''); const section = h && h !== 'mediadores' ? document.getElementById(h) : null; if (section) section.scrollIntoView(); else window.scrollTo({ top: 0, behavior: 'auto' }) }, [])
  return <div className="med"><main>
    <section className="med-hero" id="mediadores-proyecto"><div className="med-wrap med-hero__grid"><div data-reveal><a className="med-home" href="#inicio">Intranet · Gestión y Servicios</a><img className="med-logo" src={logo} alt="Mediadores de Convivencia" /><p className="med-kicker">Evolución de Gestores</p><h1>Diálogo que construye <em>convivencia</em>.</h1><p className="med-lead">Estrategia civil de la Gobernación del Valle del Cauca que trabaja desde la prevención, la mediación, la pedagogía y la articulación territorial para acercar la institucionalidad a la ciudadanía.</p><a className="med-btn" href="https://docs.google.com/presentation/d/1T3SoJQwjnmxo6mtSK20HaGyDXdOKAnt3/edit" target="_blank" rel="noreferrer">Conocer el programa <IconArrowRight width={18} height={18} /></a></div><div className="med-hero__art" data-reveal><span /><img src={heroImage} alt="Mediador de Convivencia en territorio" /></div></div></section>

    <section className="med-stats" aria-label="Mediadores en cifras"><div className="med-wrap"><p className="med-section-label">Mediadores en cifras</p><div className="med-stats__grid">{STATS.map(([value, label, period]) => <article key={label} data-reveal><strong>{value}</strong><span>{label}</span><small>{period}</small></article>)}</div></div></section>

    <section className="med-sec" id="mediadores-que-hacemos"><div className="med-wrap"><p className="med-eyebrow">Qué hacemos</p><h2>Una respuesta cercana, <em>antes y durante</em>.</h2><div className="med-do">{[['Prevenimos', 'Identificamos riesgos y desarrollamos acciones preventivas antes de que los conflictos escalen.'], ['Mediamos', 'Recibimos quejas, escuchamos a las personas y facilitamos el vínculo con las autoridades competentes.'], ['Acompañamos', 'Hacemos presencia en movilizaciones, instituciones educativas, comunidades, eventos y espacios públicos.'], ['Articulamos', 'Las articulaciones son actividades desarrolladas junto a secretarías y otras entidades.'], ['Formamos', 'Realizamos capacitaciones y pedagogía para fortalecer capacidades ciudadanas y convivencia.']].map(([title, text], i) => <article key={title} data-reveal style={{ '--d': `${i * 55}ms` }}><b>0{i + 1}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="med-sec med-activity" id="mediadores-actividades"><div className="med-wrap med-activity__grid"><div data-reveal><p className="med-eyebrow">Actividades numeradas</p><h2>Así se mueve la <em>operación</em>.</h2><p>La hoja de ruta organiza 25 actividades. Cada registro queda enumerado para facilitar el seguimiento territorial y la consolidación de resultados.</p></div><div className="med-activity__list" data-reveal><article><b>Articulaciones institucionales</b><span>Acciones en conjunto con secretarías y entidades aliadas.</span></article><article><b>Actividades institucionales</b><span>Acciones en colegios, instituciones y otros entornos institucionales.</span></article><article><b>Percepción ciudadana y escucha activa</b><span>Registro de quejas y mediación con las autoridades encargadas.</span></article><article><b>Capacitaciones</b><span>Espacios de formación para la convivencia y la gestión territorial.</span></article></div></div></section>

    <section className="med-sec med-zones" id="mediadores-zonas"><div className="med-wrap"><p className="med-eyebrow">Cobertura operativa</p><h2>Un equipo conectado en <em>ocho zonas</em>.</h2><p className="med-territory__lead">Selecciona una zona para resaltarla en el mapa operativo. Cada zona articula los municipios asignados y cuenta con una coordinación territorial.</p><div className="med-zones__grid"><div className="med-zones__map" data-reveal>{ZONES.map((item, index) => <button key={item} onClick={() => setZone(item)} className={`${item === zone ? 'is-active' : ''} med-zones__shape med-zones__shape--${index + 1}`}><span>{item}</span></button>)}</div><aside className="med-zone-detail" data-reveal><span>Zona resaltada</span><h3>{zone}</h3><p>Coordinación territorial que acompaña los municipios asignados, consolida las actividades y fortalece la conexión del equipo mediador.</p><a href="#mediadores-actividades">Ver cómo actuamos <IconArrowRight width={16} height={16} /></a></aside></div></div></section>


    <section className="med-sec med-story"><div className="med-wrap med-story__grid"><img src={teamImage} alt="Trabajo colaborativo de Mediadores de Convivencia" data-reveal /><div data-reveal><p className="med-eyebrow">Escuchar para actuar</p><h2>La escucha activa también es <em>intervención</em>.</h2><p>La presencia territorial permite identificar necesidades, recibir quejas y facilitar la mediación entre las personas y las autoridades responsables. Esa información orienta las acciones de convivencia en cada municipio.</p><p>De Gestores a Mediadores: una evolución que hace explícito el propósito de tender puentes y construir soluciones con la comunidad.</p></div></div></section>

    <section className="med-sec med-docs" id="mediadores-recursos"><div className="med-wrap"><p className="med-eyebrow">Documentación</p><h2>Información y <em>herramientas</em></h2><div className="med-docs__grid"><a href="https://docs.google.com/presentation/d/1T3SoJQwjnmxo6mtSK20HaGyDXdOKAnt3/edit" target="_blank" rel="noreferrer"><IconDownload width={20} /><span><b>Presentación Mediadores</b><small>Material institucional</small></span></a><a href="https://drive.google.com/file/d/142AKz_ybWKmxxmcVO79h1q3DwEYF9tre/view?usp=sharing" target="_blank" rel="noreferrer"><IconDownload width={20} /><span><b>Informe ejecutivo</b><small>Gestión territorial</small></span></a><a href="https://drive.google.com/file/d/1JaagvvdPJPElIOj79dqEpSR5UTS26rsz/view?usp=sharing" target="_blank" rel="noreferrer"><IconDownload width={20} /><span><b>Hoja de ruta</b><small>Orientaciones 2024–2026</small></span></a><a href="https://drive.google.com/drive/folders/1g2bZ5IQXTkmT4PnQV_mGKMwUenra7xB6" target="_blank" rel="noreferrer"><IconDownload width={20} /><span><b>Formatos</b><small>Consulta y descarga los formatos del programa</small></span></a><a href="https://drive.google.com/drive/folders/1ANQphRg7qNoqI2ClJvsOqSCBnOEvlid3" target="_blank" rel="noreferrer"><IconDownload width={20} /><span><b>Imágenes y logos</b><small>Recursos gráficos de Mediadores</small></span></a></div></div></section>
  </main></div>
}
