import { useEffect } from 'react'
import PlatformSection from '../../components/PlatformSection.jsx'
import { IconArrowRight, IconCheck, IconDownload, IconExternal } from '../../components/Icons.jsx'
import { useReveal } from '../../lib/useReveal.js'
import { Skyline, Hoja } from './deco.jsx'
import { CIFRAS_PERIODO, CIFRAS_RESUMEN, COLORES, EJES, OBJETIVOS, OBJETIVO_GENERAL, PROJECT, RECURSOS } from './data.js'
import gysLogo from '../../assets/gys_logo.png'
import logoMCB from '../../assets/mi-cali-bella/logo.png'
import bellaSaluda from '../../assets/mi-cali-bella/bella-saluda.png'
import bellaFrente from '../../assets/mi-cali-bella/bella-frente.png'
import bellaVuela from '../../assets/mi-cali-bella/bella-vuela.png'
import bellaFeliz from '../../assets/mi-cali-bella/bella-feliz.png'
import bellaMusica from '../../assets/mi-cali-bella/bella-musica.png'
import bellaSilba from '../../assets/mi-cali-bella/bella-silba.png'
import bellaUaesp from '../../assets/mi-cali-bella/bella-saluda-uaesp.png'
import './promotores.css'

const POSES = [{ src: bellaFrente, alt: 'Bella de frente' }, { src: bellaVuela, alt: 'Bella volando' }, { src: bellaFeliz, alt: 'Bella feliz' }, { src: bellaMusica, alt: 'Bella con música' }, { src: bellaSilba, alt: 'Bella silbando' }, { src: bellaUaesp, alt: 'Bella con gorra UAESP' }]

export default function PromotoresPage() {
  useReveal()
  useEffect(() => { const h = window.location.hash.replace(/^#/, ''); const target = h && h !== 'promotores' ? document.getElementById(h) : null; if (target) target.scrollIntoView(); else window.scrollTo({ top: 0, behavior: 'auto' }) }, [])
  return <div className="mcb"><main className="mcb-main">
    <section className="mcb-hero" id="promotores-proyecto"><span className="mcb-hero__blob mcb-hero__blob--a" /><span className="mcb-hero__blob mcb-hero__blob--b" /><Skyline className="mcb-hero__skyline" /><div className="mcb-hero__inner"><div className="mcb-hero__text" data-reveal><a className="mcb-cobrand" href="#inicio"><img src={gysLogo} alt="Gestión y Servicios" /></a><img className="mcb-hero__logo" src={logoMCB} alt={`${PROJECT.nombre}: ${PROJECT.sub}`} /><p className="mcb-hero__lema">{PROJECT.lema}</p><p className="mcb-hero__desc">Somos la estrategia con la que Santiago de Cali recupera sus espacios públicos: pedagogía, prevención y control en el manejo de residuos sólidos.</p><div className="mcb-hero__cta"><a className="mcb-btn mcb-btn--primary" href="#promotores-territorio">Ver cobertura <IconArrowRight width={18} height={18} /></a><a className="mcb-btn mcb-btn--ghost" href="#promotores-objetivos">Conocer el proyecto</a></div></div><div className="mcb-hero__art" data-reveal><span className="mcb-hero__disc" /><img className="mcb-hero__bella" src={bellaSaluda} alt="Bella, mascota del proyecto" /></div></div></section>
    <section className="mcb-ficha"><div className="mcb-wrap mcb-ficha__grid">{CIFRAS_RESUMEN.map((item, i) => <article className={`mcb-stat mcb-stat--${item.tone}`} key={item.label} data-reveal style={{ '--d': `${i * 70}ms` }}><span className="mcb-stat__value">{item.value}</span><span className="mcb-stat__unit">{item.unit}</span><span className="mcb-stat__label">{item.label}</span></article>)}</div><p className="mcb-ficha__nota">Cifras de la operación · {CIFRAS_PERIODO}</p></section>
    <section className="mcb-sec mcb-sec--objetivos" id="promotores-objetivos"><div className="mcb-wrap"><SecTitle eyebrow="El proyecto">Recuperamos la <em>gobernanza</em> del espacio público</SecTitle><p className="mcb-lead" data-reveal>{OBJETIVO_GENERAL}</p><div className="mcb-obj">{OBJETIVOS.map((item, i) => <article className="mcb-obj__card" key={item.n} data-reveal style={{ '--d': `${i * 90}ms` }}><span className="mcb-obj__n">{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><p className="mcb-ejes-intro" data-reveal>Tres ejes, una misma meta: recuperar, cuidar y transformar hábitos en cada comunidad.</p><ul className="mcb-lineas">{EJES.map((item, i) => <li key={item.id} data-reveal style={{ '--d': `${i * 70}ms` }}><Hoja className="mcb-lineas__icon" /><h4>{item.title}</h4><p>{item.text}</p></li>)}</ul></div></section>
    <section className="mcb-sec mcb-sec--territorio" id="promotores-territorio"><div className="mcb-wrap"><SecTitle eyebrow="Cobertura territorial" center>Acciones que se ven en <em>toda Cali</em></SecTitle><p className="mcb-lead mcb-lead--center" data-reveal>Presencia en las 22 comunas y 377 barrios y sectores priorizados. El mapa organiza los resultados por eje de trabajo.</p><TerritoryMap /></div></section>
    <section className="mcb-sec mcb-sec--bella" id="promotores-bella"><div className="mcb-wrap mcb-bella"><div className="mcb-bella__text"><SecTitle eyebrow="Mascota" light>¡Hola, soy <em>Bella</em>!</SecTitle><p data-reveal>Integro el proyecto Promotores Mi Cali Bella y acompaño la sensibilización ciudadana sobre el manejo adecuado de residuos sólidos.</p><p data-reveal>Como torito cabecirrojo, invito a cada persona a recuperar Cali con hábitos que cuidan el entorno.</p></div><ul className="mcb-poses">{POSES.map((pose, i) => <li key={pose.alt} data-reveal style={{ '--d': `${i * 55}ms` }}><img src={pose.src} alt={pose.alt} loading="lazy" /></li>)}</ul></div></section>
    <section className="mcb-sec mcb-sec--marca" id="promotores-marca"><div className="mcb-wrap"><SecTitle eyebrow="Manual de marca" center>Identidad <em>visual</em></SecTitle><p className="mcb-lead mcb-lead--center" data-reveal>El verde expresa frescura, vitalidad y la energía de una comunidad que transforma su entorno.</p><div className="mcb-marca"><article className="mcb-card" data-reveal><h3 className="mcb-card__title">Colorimetría</h3><ul className="mcb-colores">{COLORES.map(color => <li key={color.hex}><span className="mcb-color" style={{ background: color.hex }} /><span className="mcb-color__info"><strong>{color.name}</strong><code>{color.hex}</code><em>{color.detail}</em></span></li>)}</ul></article><article className="mcb-card" data-reveal style={{ '--d': '90ms' }}><h3 className="mcb-card__title">Tipografía</h3><p className="mcb-tipo">Mohr Rounded</p><p className="mcb-tipo__note">Para el logosímbolo y las piezas gráficas del proyecto.</p><p className="mcb-tipo mcb-tipo--alt">Poppins</p><p className="mcb-tipo__note">Para papelería, membretes y presentaciones corporativas.</p><ul className="mcb-checks"><li><IconCheck width={15} height={15} /> Black / ExtraBold en títulos</li><li><IconCheck width={15} height={15} /> SemiBold en subtítulos y botones</li></ul></article><article className="mcb-card" data-reveal style={{ '--d': '180ms' }}><h3 className="mcb-card__title">Sistema visual</h3><p className="mcb-card__lead">Una identidad amable y reconocible que une a Bella, la ciudad y el mensaje de residuos cero.</p><ul className="mcb-visual"><li><strong>Bella</strong><span>La voz cercana que acompaña la conversación ciudadana.</span></li><li><strong>Formas orgánicas</strong><span>Conectan naturaleza, movimiento y vida urbana.</span></li><li><strong>Verdes de la marca</strong><span>Dan unidad a las piezas en territorio y canales digitales.</span></li></ul></article></div></div></section>
    <PlatformSection id="promotores-plataforma" title="Conoce nuestra plataforma" text="La plataforma de Promotores Mi Cali Bella concentra la operación digital del proyecto. Ingresa con tu usuario para acceder." url="https://frontend-production-9828.up.railway.app/login" style={{ '--pf-accent': '#2c6b1f', '--pf-deep': '#215c53', '--pf-soft': '#f4f8ee', '--pf-ink': '#1d2b28' }} />
    <section className="mcb-sec mcb-sec--recursos" id="promotores-recursos"><div className="mcb-wrap"><SecTitle eyebrow="Descargas" center>Recursos y <em>plantillas</em></SecTitle><p className="mcb-lead mcb-lead--center" data-reveal>Todo lo necesario para aplicar la marca con claridad y consistencia.</p><ul className="mcb-recursos">{RECURSOS.map((item, i) => <li key={item.id} data-reveal style={{ '--d': `${i * 50}ms` }}><a className="mcb-rec" href={item.url} target="_blank" rel="noreferrer"><span className="mcb-rec__icon">{item.externo ? <IconExternal width={20} height={20} /> : <IconDownload width={20} height={20} />}</span><span className="mcb-rec__body"><strong>{item.title}</strong><em>{item.desc}</em><span className="mcb-rec__tipo">{item.tipo}</span></span></a></li>)}</ul></div></section>
  </main><footer className="mcb-foot"><div className="mcb-wrap mcb-foot__inner"><img className="mcb-foot__logo" src={logoMCB} alt="" /><p className="mcb-foot__legal">{PROJECT.nombre}: {PROJECT.sub}</p></div></footer></div>
}
function TerritoryMap() { const areas = [{ name: 'Norte', cls: 'north', tag: '22 comunas' }, { name: 'Occidente', cls: 'west', tag: '377 sectores' }, { name: 'Centro', cls: 'center', tag: '514.708 m²' }, { name: 'Oriente', cls: 'east', tag: '342.915 personas' }, { name: 'Sur', cls: 'south', tag: '3 ejes' }]; return <div className="mcb-map" data-reveal><div className="mcb-map__shape"><span className="mcb-map__river" />{areas.map(area => <div className={`mcb-map__area mcb-map__area--${area.cls}`} key={area.name}><strong>{area.name}</strong><span>{area.tag}</span></div>)}</div><div className="mcb-map__summary"><p className="mcb-map__eyebrow">Resultados por eje</p><MapResult tone="rep" title="Recuperación del espacio público" text="514.708 m² recuperados mediante intervenciones en puntos priorizados." /><MapResult tone="care" title="Cuidadores" text="169.546 personas sensibilizadas para cuidar los espacios recuperados." /><MapResult tone="ped" title="Pedagogía" text="173.369 personas sensibilizadas sobre el manejo adecuado de residuos." /></div></div> }
function MapResult({ tone, title, text }) { return <article><span className={`mcb-map__dot mcb-map__dot--${tone}`} /><div><strong>{title}</strong><p>{text}</p></div></article> }
function SecTitle({ eyebrow, children, center, light }) { return <div className={`mcb-title ${center ? 'is-center' : ''} ${light ? 'is-light' : ''}`} data-reveal><span className="mcb-title__eyebrow"><Hoja width={14} height={14} />{eyebrow}</span><h2 className="mcb-title__h">{children}</h2></div> }
