import { useEffect } from 'react'
import { IconArrowRight, IconCheck, IconDownload, IconExternal, IconFileText, IconShield, IconStar } from '../../components/Icons.jsx'
import { useReveal } from '../../lib/useReveal.js'
import { ASSETS, FORMATS, LINKS, QUALITY, SST } from './data.js'
import './gys.css'
const Resource = ({ item, index }) => <li data-reveal style={{ '--d': `${index * 45}ms` }}><a className="gys-resource" href={item[1]} target="_blank" rel="noreferrer"><span className="gys-resource__icon"><IconFileText width={20} height={20}/></span><strong>{item[0]}</strong><IconExternal className="gys-resource__go" width={17} height={17}/></a></li>
export default function GysPage() {
  useReveal()
  useEffect(() => { const target = document.getElementById(window.location.hash.slice(1)); if (target && target.id !== 'gys') target.scrollIntoView(); else window.scrollTo({ top: 0, behavior: 'auto' }) }, [])
  const values = [['01','Trabajo en equipo','Construimos resultados respetando ideas y compartiendo conocimiento.'],['02','Servicio al cliente','Escuchamos y respondemos para ser aliados de confianza.'],['03','Liderazgo','Proponemos soluciones y generamos impacto positivo.'],['04','Responsabilidad','Actuamos con compromiso, transparencia y mejora continua.']]
  return <div className="gys-page"><main>
    <section className="gys-hero" id="gys"><div className="gys-wrap gys-hero__grid"><div className="gys-hero__copy" data-reveal><a className="gys-hero__back" href="#inicio">‹ Volver a la intranet</a><img className="gys-hero__logo" src={ASSETS.logo} alt="Gestión y Servicios"/><p className="gys-overline">INTRANET CORPORATIVA</p><h1>Personas que hacen que todo <em>funcione.</em></h1><p className="gys-hero__lead">Soluciones integrales en talento humano y procesos de apoyo para que nuestros clientes y equipo avancen con confianza.</p><div className="gys-hero__actions"><a className="gys-btn gys-btn--primary" href="#gys-formatos">Ir a formatos <IconArrowRight width={18} height={18}/></a><a className="gys-btn gys-btn--quiet" href="#gys-sst">Seguridad y salud</a></div></div><div className="gys-hero__image" data-reveal><img src={ASSETS.team} alt="Equipo de Gestión y Servicios"/><span className="gys-hero__seal"><strong>+ valor</strong><small>para las personas</small></span></div></div></section>
    <section className="gys-shortcuts"><div className="gys-wrap gys-shortcuts__grid">{LINKS.map((l,i)=><a href={l.href} className={`gys-shortcut gys-shortcut--${l.tone}`} key={l.title} data-reveal style={{ '--d':`${i*70}ms` }}><span><strong>{l.title}</strong><small>{l.text}</small></span><IconArrowRight width={20} height={20}/></a>)}</div></section>
    <section className="gys-section"><div className="gys-wrap gys-about__grid"><div data-reveal><p className="gys-eyebrow">Sobre nosotros</p><h2>Hacemos sencilla la gestión que mueve a las organizaciones.</h2></div><div className="gys-about__text" data-reveal><p>Somos una aliada estratégica que brinda soluciones eficientes y oportunas en la administración del talento humano y la gestión de procesos.</p><p>Trabajamos con altos estándares de calidad, cercanía y automatización para facilitar la operación de nuestros clientes.</p><a href="#gys-calidad" className="gys-text-link">Conoce nuestro sistema de calidad <IconArrowRight width={16} height={16}/></a></div></div></section>
    <section className="gys-section gys-values"><div className="gys-wrap"><p className="gys-eyebrow">Nuestra esencia</p><h2>Cuatro valores, una forma de trabajar.</h2><div className="gys-values__grid">{values.map(([n,t,d],i)=><article className="gys-value" key={t} data-reveal style={{ '--d':`${i*60}ms` }}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className="gys-section gys-section--paper" id="gys-formatos"><div className="gys-wrap"><div className="gys-section__head"><div><p className="gys-eyebrow">Gestión ágil</p><h2>Formatos y solicitudes.</h2><p>Los documentos que necesitas para gestionar tu día a día.</p></div><IconDownload className="gys-section__mark" width={42} height={42}/></div><ul className="gys-resources">{FORMATS.map((x,i)=><Resource item={x} index={i} key={x[0]}/>)}</ul></div></section>
    <section className="gys-section" id="gys-calidad"><div className="gys-wrap gys-two-col"><div className="gys-panel" data-reveal><IconCheck width={27} height={27}/><p className="gys-eyebrow">Sistema de gestión</p><h2>Calidad en cada proceso.</h2><p>Lineamientos que orientan nuestro compromiso de mejorar continuamente.</p><a className="gys-btn gys-btn--white" href="https://docs.google.com/forms/d/e/1FAIpQLSdgpsG4jIFDviBW30zIrVOGDa9QRsIr-pKrfUS5yK4XKOo0Pg/viewform" target="_blank" rel="noreferrer">Reportar salida no conforme <IconExternal width={16} height={16}/></a></div><ul className="gys-resources gys-resources--plain">{QUALITY.map((x,i)=><Resource item={x} index={i} key={x[0]}/>)}</ul></div></section>
    <section className="gys-section gys-section--sst" id="gys-sst"><div className="gys-wrap gys-two-col"><div><p className="gys-eyebrow">Bienestar y prevención</p><h2>Seguridad y salud en el trabajo.</h2><p className="gys-section__intro">Recursos para promover un entorno laboral seguro, saludable y productivo.</p><ul className="gys-resources gys-resources--plain">{SST.map((x,i)=><Resource item={x} index={i} key={x[0]}/>)}</ul></div><aside className="gys-accident" data-reveal><IconShield width={32} height={32}/><p className="gys-eyebrow">¿Tuviste un accidente laboral?</p><h3>Repórtalo de inmediato.</h3><ol><li>Notifica a tu jefe o responsable.</li><li>Contacta a Gestión Humana en las primeras 48 horas.</li><li>Envía incapacidad e historia clínica.</li></ol><a className="gys-btn gys-btn--primary" href="mailto:incapacidadesys@gestionyservicios.com.co">Solicitar orientación <IconArrowRight width={17} height={17}/></a></aside></div></section>
    <section className="gys-final"><div className="gys-wrap gys-final__inner"><img src={ASSETS.vertical} alt=""/><div><p className="gys-eyebrow">Gestión y Servicios</p><h2>Gestión hecha con humanidad.</h2></div><a href="#gys"><IconStar width={20} height={20}/> Volver arriba</a></div></section>
  </main></div>
}
